### ISSUE TITLE
HU06 - Consultar la información detallada de coleccionista

### ISSUE THREAD

**Issue by brayanhenao** [Miso-Code/misw4203-moviles-2023#6]
Como usuario visitante quiero ver el detalle de un coleccionista para conocer sus gustos musicales

**Criterios de Aceptación**

- [x]  Se muestra el nombre completo, teléfono y correo electrónico del coleccionista así como la lista de sus álbumes favoritos y la lista de sus artistas favoritos
- [x]  La lista de álbumes favoritos debe contener la misma información que en: #1 
- [x]  La lista de artistas favoritos debe contener la misma información que en: #3 
- [x]  Al hacer click sobre el elemento de la lista de albumes favoritos se debe redirigir a la vista de detalle del album: #2 
- [x]  Al hacer click sobre el elemento de la lista de artistas favoritos se debe redirigir a la vista de detalle del artista: #4

**Comment by ocralo** [comment]
![Image](https://user-images.githubusercontent.com/25392457/229319506-cfa83e2b-df42-44dd-a82d-763bbf375bc0.png)
